### ISSUE TITLE
Installation fails in v1.0.71 when installing without dev dependencies

### ISSUE THREAD

**Issue by jspizziri** [edrlab/r2-shared-js#57]
[This commit introduced a `postinstall` command](https://github.com/readium/r2-shared-js/commit/2a4bf179081364958aa93c7b634c1c14c6f14cd7#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R105). That command depends on `rimraf` which is listed as a `devDependency`. This causes an install failure when attempting to install this package without the `devDependencies` which would be traditional in a production build.

**Comment by danielweck** [comment]
well spotted, thank you very much for letting us know. ironically, the offending npm package is deleted because of build-time errors, it is not problematic at runtime. instead of moving rimraf to devdeps, I am wondering whether we could just capture a non-zero exit code and fallback gracefully to a co-op (e.g. || echo noop)

**Comment by danielweck** [comment]
ps: ultimately, the better fix would be to remove this postinstall workaround, and instead swap the antiquated ava dependency for vitest or another modern test runner {I believe types/glob is a transitive dep via ava)

**Comment by AntonOfTheWoods** [comment]
BTW, this also causes installing with `pnpm` to fail, and as a result makes using this library extremely inconvenient in many situations where network is an issue, due to `npm` being fundamentally broken...

**Comment by danielweck** [comment]
Sorry this took so long to fix. Hopefully this works:

https://github.com/readium/r2-shared-js/commit/57549fd198ddb2d00ae2437947c3b8cdfa24471c

**Comment by AntonOfTheWoods** [comment]
Thanks @danielweck , `pnpm` is now able to install the package just fine!
