### ISSUE TITLE
epub-type can be dropped / removed from model

### ISSUE THREAD

**Issue by danielweck** [edrlab/r2-shared-js#9]
https://github.com/readium/r2-shared-js/blob/44ebead56f6a4e0575c384ddf55cf42c8527f6d6/src/models/metadata.ts#L117

**Comment by danielweck** [comment]
https://github.com/readium/r2-shared-js/blob/9de704bf1ea17be1c23748b3f00bd61da469c64a/src/models/metadata.ts#L278-L283

**Comment by HadrienGardeur** [comment]
This is IMO already covered by `@type`.
